files:
  - source: /*/src/*/resources/assets/*/lang/en_us.json
    translation: "%original_path%/%locale_with_underscore%.json"
    ignore: [/*/src/test*/**/*]
preserve_hierarchy: true
project_id: "647524"
